# Generated by Django 5.2.7 on 2025-11-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordchangeverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email đăng ký')),
                ('ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(blank=True, max_length=20, null=True, verbose_name='CCCD')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Mật khẩu đã hash')),
                ('otp_code', models.CharField(max_length=6, verbose_name='Mã OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Registration',
                'verbose_name_plural': 'OTP Registrations',
            },
        ),
    ]
