# Generated by Django 5.2.5 on 2025-11-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='nhanvien/', verbose_name='Ảnh đại diện')),
                ('ho_ten', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('chuc_vu', models.CharField(choices=[('KE_TOAN', 'Kế toán'), ('NHAN_VIEN', 'Nhân viên'), ('TAI_XE', 'Tài xế'), ('PHU_XE', 'Phụ xe')], default='NHAN_VIEN', max_length=20, verbose_name='Chức vụ')),
                ('ngay_vao_lam', models.DateField(auto_now_add=True, verbose_name='Ngày vào làm')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
            },
        ),
    ]
