# Generated by Django 5.2.5 on 2025-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nhanvien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'ordering': ['-ngay_vao_lam'], 'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='user',
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='dia_chi',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='ghi_chu',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='luong_co_ban',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='chuc_vu',
            field=models.CharField(choices=[('QUAN_LY', 'Quản lý'), ('NHAN_VIEN', 'Nhân viên'), ('TAI_XE', 'Tài xế'), ('PHUC_VU', 'Phục vụ')], default='NHAN_VIEN', max_length=20, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='so_dien_thoai',
            field=models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
