# Generated by Django 5.2.5 on 2025-11-04 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(max_length=50)),
                ('trang_thai', models.CharField(choices=[('THANH_CONG', 'Thành công'), ('THAT_BAI', 'Thất bại'), ('CHO_XU_LY', 'Chờ xử lý')], default='CHO_XU_LY', max_length=20)),
                ('ngay_gio', models.DateTimeField(auto_now_add=True)),
                ('ma_giao_dich', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
            },
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien_so', models.CharField(max_length=20, unique=True)),
                ('loai_xe', models.CharField(max_length=50)),
                ('so_ghe', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Xe',
                'verbose_name_plural': 'Xe',
            },
        ),
        migrations.CreateModel(
            name='Tuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_di', models.CharField(max_length=100)),
                ('diem_den', models.CharField(max_length=100)),
                ('khoang_cach', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tuyến',
                'verbose_name_plural': 'Tuyến',
                'unique_together': {('diem_di', 'diem_den')},
            },
        ),
        migrations.CreateModel(
            name='Chuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gio_khoi_hanh', models.DateTimeField()),
                ('ngay_gio_den', models.DateTimeField(blank=True, null=True)),
                ('tong_so_ve', models.PositiveIntegerField()),
                ('gia_ve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyens', to='booking.tuyen')),
            ],
            options={
                'verbose_name': 'Chuyến xe',
                'verbose_name_plural': 'Chuyến xe',
            },
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField()),
                ('trang_thai', models.CharField(choices=[('CHO_THANH_TOAN', 'Chờ thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán'), ('DA_HUY', 'Đã hủy')], default='CHO_THANH_TOAN', max_length=20)),
                ('thoi_gian_dat', models.DateTimeField(auto_now_add=True)),
                ('chuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ves', to='booking.chuyen')),
            ],
            options={
                'verbose_name': 'Vé',
                'verbose_name_plural': 'Vé',
            },
        ),
    ]
