# Generated by Django 5.2.5 on 2025-11-04 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve',
            name='khach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ves', to='users.khachhang'),
        ),
        migrations.AddField(
            model_name='thanhtoan',
            name='ve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_toan', to='booking.ve'),
        ),
        migrations.AddField(
            model_name='chuyen',
            name='xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyens', to='booking.xe'),
        ),
    ]
