# Generated by Django 5.2.7 on 2025-11-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_add_seat_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ve',
            name='vi_tri_ghe',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách vị trí ghế đã chọn, ví dụ: ["A1", "A2", "B3"]'),
        ),
    ]
