# Generated by Django 5.2.5 on 2025-11-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_ve_vi_tri_ghe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chuyen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xe',
            options={},
        ),
    ]
