# Generated by Django 5.2.5 on 2025-11-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_chuyen_options_alter_xe_options'),
        ('users', '0002_passwordchangeverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyen',
            name='gia_ve',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá vé'),
        ),
        migrations.AlterField(
            model_name='chuyen',
            name='ngay_gio_den',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ đến'),
        ),
        migrations.AlterField(
            model_name='chuyen',
            name='ngay_gio_khoi_hanh',
            field=models.DateTimeField(verbose_name='Ngày giờ khởi hành'),
        ),
        migrations.AlterField(
            model_name='chuyen',
            name='tong_so_ve',
            field=models.PositiveIntegerField(verbose_name='Tổng số vé'),
        ),
        migrations.AlterField(
            model_name='chuyen',
            name='tuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyens', to='booking.tuyen', verbose_name='Tuyến'),
        ),
        migrations.AlterField(
            model_name='chuyen',
            name='xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chuyens', to='booking.xe', verbose_name='Xe'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='ma_giao_dich',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='ngay_gio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày giờ'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='phuong_thuc',
            field=models.CharField(max_length=50, verbose_name='Phương thức'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='trang_thai',
            field=models.CharField(choices=[('THANH_CONG', 'Thành công'), ('THAT_BAI', 'Thất bại'), ('CHO_XU_LY', 'Chờ xử lý')], default='CHO_XU_LY', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='ve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_toan', to='booking.ve', verbose_name='Vé'),
        ),
        migrations.AlterField(
            model_name='tuyen',
            name='diem_den',
            field=models.CharField(max_length=100, verbose_name='Điểm đến'),
        ),
        migrations.AlterField(
            model_name='tuyen',
            name='diem_di',
            field=models.CharField(max_length=100, verbose_name='Điểm đi'),
        ),
        migrations.AlterField(
            model_name='tuyen',
            name='khoang_cach',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Khoảng cách (km)'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='chuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ves', to='booking.chuyen', verbose_name='Chuyến'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='khach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ves', to='users.khachhang', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='so_luong',
            field=models.PositiveIntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='xe',
            name='bien_so',
            field=models.CharField(max_length=20, unique=True, verbose_name='Biển số'),
        ),
        migrations.AlterField(
            model_name='xe',
            name='loai_xe',
            field=models.CharField(max_length=50, verbose_name='Loại xe'),
        ),
        migrations.AlterField(
            model_name='xe',
            name='so_ghe',
            field=models.PositiveIntegerField(verbose_name='Số ghế'),
        ),
    ]
