# Generated by Django 5.2.5 on 2025-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_chuyen_gia_ve_alter_chuyen_ngay_gio_den_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thanhtoan',
            name='so_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='trang_thai',
            field=models.CharField(choices=[('THANH_CONG', 'Thành công'), ('THAT_BAI', 'Thất bại'), ('CHO_XU_LY', 'Chờ xử lý'), ('CHO_THANH_TOAN', 'Chờ thanh toán')], default='CHO_XU_LY', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
