# Generated by Django 5.2.5 on 2025-11-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_thanhtoan_so_tien_alter_thanhtoan_trang_thai'),
        ('users', '0004_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_voucher', models.CharField(max_length=20, unique=True, verbose_name='Mã voucher')),
                ('ten_voucher', models.CharField(max_length=200, verbose_name='Tên voucher')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('loai_giam_gia', models.CharField(choices=[('PHAN_TRAM', 'Phần trăm'), ('SO_TIEN', 'Số tiền cố định')], default='PHAN_TRAM', max_length=20)),
                ('gia_tri_giam', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá trị giảm')),
                ('giam_toi_da', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giảm tối đa (đ)')),
                ('gia_tri_don_toi_thieu', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá trị đơn tối thiểu')),
                ('ngay_bat_dau', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('so_luong', models.IntegerField(default=100, verbose_name='Số lượng voucher')),
                ('da_su_dung', models.IntegerField(default=0, verbose_name='Đã sử dụng')),
                ('so_lan_su_dung_toi_da_moi_user', models.IntegerField(default=1, verbose_name='Số lần dùng/user')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('khach_hang_duoc_su_dung', models.ManyToManyField(blank=True, related_name='vouchers_nhan', to='users.khachhang', verbose_name='Khách hàng được sử dụng')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='VoucherSuDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien_giam', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ngay_su_dung', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.khachhang')),
                ('ve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_da_dung', to='booking.ve')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_su_dung', to='booking.voucher')),
            ],
            options={
                'verbose_name': 'Lịch sử voucher',
                'verbose_name_plural': 'Lịch sử vouchers',
                'ordering': ['-ngay_su_dung'],
            },
        ),
    ]
