# Generated by Django 5.2.5 on 2025-11-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_voucher_vouchersudung'),
        ('users', '0005_alter_nhanvien_options_remove_nhanvien_user_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='ve',
            name='chuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ves', to='booking.chuyen'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='khach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ves', to='users.khachhang'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='so_luong',
            field=models.IntegerField(default=1, verbose_name='Số lượng vé'),
        ),
        migrations.AlterField(
            model_name='ve',
            name='trang_thai',
            field=models.CharField(choices=[('CHO_THANH_TOAN', 'Chờ thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán'), ('DA_HUY', 'Đã hủy'), ('HET_HAN', 'Hết hạn')], default='CHO_THANH_TOAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='ve',
            name='vi_tri_ghe',
            field=models.JSONField(default=list, verbose_name='Vị trí ghế'),
        ),
    ]
