# Generated by Django 5.2.5 on 2025-11-30 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_ve_thoi_gian_dat_ve_han_thanh_toan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve',
            name='ngay_dat',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 30, 19, 28, 40, 864004, tzinfo=datetime.timezone.utc), verbose_name='Ngày đặt'),
            preserve_default=False,
        ),
    ]
