# Generated by Django 5.2.7 on 2025-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_ve_thoi_gian_dat_ve_han_thanh_toan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ve',
            name='thoi_gian_dat',
        ),
        migrations.AddField(
            model_name='ve',
            name='han_thanh_toan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn thanh toán'),
        ),
    ]
