"""
Django settings for BookingTicket project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z=q*#9+5ct)6@3z--yeaixj7fg6sd=*tf1-3^origjz6v7-4ld'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'booking',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Auto-logout middleware: checks last activity and logs out inactive users
    'users.middleware.AutoLogoutMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BookingTicket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BookingTicket.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # vẫn để mysql vì Django không có backend riêng cho MariaDB
        'NAME': 'bookingticket',                 # schema bạn đã tạo
        'USER': 'root',                        # user của MariaDB (mặc định là root)
        'PASSWORD': '03062005',                 # mật khẩu root (đã cập nhật theo HelixSQL)
        'HOST': '127.0.0.1',                   # localhost
        'PORT': '3307',                        # port MariaDB (có thể là 3306 hoặc 3307)
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Múi giờ Việt Nam
USE_TZ = True  # Bật timezone-aware datetime

AUTH_USER_MODEL = 'users.Account'

LOGIN_URL = 'login'

SESSION_COOKIE_AGE = 3600  # 1 hour instead of 5 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = False  # Set True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attacks
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_SAVE_EVERY_REQUEST = True 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

AUTO_LOGOUT_DELAY = 3600  # Match session timeout

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'thaibinh03062005@gmail.com'
EMAIL_HOST_PASSWORD = 'hpwa swyw zwcu bjbe'
DEFAULT_FROM_EMAIL = f'BookingTicket System <{EMAIL_HOST_USER}>'

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailBackend', # Backend tùy chỉnh của chúng ta
    'django.contrib.auth.backends.ModelBackend', # Giữ lại backend mặc định
]

#Email Timeout
EMAIL_TIMEOUT = 60

# Email verification settings
EMAIL_VERIFICATION_EXPIRE_HOURS = 1  # Token expires after 1 hour
PASSWORD_RESET_EXPIRE_HOURS = 1  # Password reset link expires after 1 hour
PASSWORD_CHANGE_EXPIRE_MINUTES = 30  # Password change link expires after 30 minutes
OTP_EXPIRE_MINUTES = 10  # OTP expires after 10 minutes

#Payment
VNPAY_CONFIG = {
    "TmnCode": "9HZKBNNN",
    "HashSecret": "8HGHV2MT8QI5NLICKG28HOBLJ0AATIE6",
    "BaseUrl": "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html",
    "Version": "2.1.0",
    "Command": "pay",
    "CurrCode": "VND",
    "Locale": "vn",
    "ReturnUrl": "http://127.0.0.1:8000/payment/callback_vnpay" # Sửa lại port cho đúng Django
}

# CELERY SETTINGS
CELERY_TASK_ALWAYS_EAGER = True  # Chạy đồng bộ (không cần Redis)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = 'cache+memory://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'